# Generated by Django 5.0.2 on 2024-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0002_rename_tag_tag_name_remove_quote_author_quote_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.ManyToManyField(to='quoteapp.author'),
        ),
    ]
